import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ShinyProvider } from "@/contexts/shiny-context";
import { cn } from "@/lib/utils";
import { Toaster } from "@ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(geistSans.variable, geistMono.variable, "antialiased")}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					storageKey="pgtrail-theme"
				>
					<ShinyProvider>
						<div className="flex min-h-dvh flex-col">
							<Header />
							<main className="mt-22 flex-1 px-4">{children}</main>
							<Footer />
						</div>
						<Toaster position="top-center" richColors />
					</ShinyProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
